### ISSUE TITLE
Term info not loading

### ISSUE THREAD

**Issue by mmc46** [VirtualFlyBrain/VFB#1059]
Main site, only affects some pages.
Chrome Version 55.0.2883.95 (64-bit)

![pasted image at 2017_01_31 10_19](https://cloud.githubusercontent.com/assets/1872083/22460977/56def678-e79f-11e6-8742-317e34fa438b.png)

Support info:
http://www.virtualflybrain.org/site/stacks/index.htm
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36 Size:[2412,956]
!M56-0.1!e2eZ!e8e-17!M1511,255,108!E!B Template!G!H2!2S!20!2i!6!H2!F5!G!H3!2S!20!2i!6!H3!F5!G!P3!0

**Comment by Robbie1977** [comment]
Example ID: FBbt_00110152

**Comment by Robbie1977** [comment]
Query being (wrongly) run as individual:
```
[uk.ac.ed.vfb.dao.client_server.Server:140] Query: individual&FBbt_00110330 2017-01-31 10:16:34,334 (www.virtualflybrain.org) INFO [uk.ac.ed.vfb.dao.client_server.server_includes.DLQueryServer:103] DLQueryServer returning 0 result(s)
```

**Comment by mmc46** [comment]
Issue with all subclasses of FBbt_00110148 'octopaminergic VPM neuron'

**Comment by Robbie1977** [comment]
checking the OWL

**Comment by Robbie1977** [comment]
@dosumis can you see anything odd in the definitions as I can't see anything odd about them

**Comment by dosumis** [comment]
> @dosumis can you see anything odd in the definitions as I can't see anything odd about them

These look fine in http://purl.obolibrary.org/obo/fbbt/2016-12-08/fbbt...

Where-else should I be looking?  Assume this is not yet running from OLS Neo.  Not keen to go poking round in VFB 1 logs.  Any idea on the scale of this issue?

**Comment by Robbie1977** [comment]
the neo side works fine but still can't switch as still missing bits.

**Comment by dosumis** [comment]
Also bit confused about the query thing.  The query for subclasses of FBbt_00110148 'octopaminergic VPM neuron' seems to [work fine](http://www.virtualflybrain.org/do/ont_bean_list.html?action=subclass&id=FBbt:00110148).  It's just clicking through from the results to term info that has problems.    Why should that need an extra query?

**Comment by Robbie1977** [comment]
```
2017-01-31 10:37:44,837 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00110160
2017-01-31 10:37:44,838 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00110160 octopaminergic VUMd neuron TPB: null]
Jan 31, 2017 10:38:01 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet springmvc threw exception
java.lang.OutOfMemoryError: Java heap space
```

**Comment by Robbie1977** [comment]
Still looking....

**Comment by Robbie1977** [comment]
```
2017-01-31 11:09:19,381 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00040048
2017-01-31 11:09:19,381 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00040048 superior clamp TPB: null]
2017-01-31 11:09:19,793 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00003748
2017-01-31 11:09:19,793 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00003748 medulla TPB: null]
2017-01-31 11:09:29,014 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00007453
2017-01-31 11:09:29,014 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00007453 pedunculus of adult mushroom body TPB: null]
2017-01-31 11:10:00,206 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00003684
2017-01-31 11:10:00,206 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00003684 adult mushroom body TPB: null]
2017-01-31 11:10:05,355 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00110148
2017-01-31 11:10:05,355 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00110148 octopaminergic VPM neuron TPB: null]
2017-01-31 11:10:07,769 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00110148
2017-01-31 11:10:07,769 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00110148 octopaminergic VPM neuron TPB: null]
2017-01-31 11:10:36,660 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00110153
2017-01-31 11:10:36,661 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00110153 octopaminergic VPM5 neuron TPB: null]
Jan 31, 2017 11:10:51 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet springmvc threw exception
java.lang.OutOfMemoryError: Java heap space

2017-01-31 11:12:18,399 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00045003
2017-01-31 11:12:18,400 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00045003 accessory medulla TPB: null]
2017-01-31 11:17:00,570 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00003748
2017-01-31 11:17:00,571 (www.virtualflybrain.org) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00003748 medulla TPB: null]
```
seems to just be with that term

**Comment by dosumis** [comment]
null = empty beans?   But this can't be the case given the bean contents that are visible in search results.

Or if the issue is Java heap space, can you just allocate more?

**Comment by Robbie1977** [comment]
I could but odd it occurs on these record alone on multiple servers

**Comment by dosumis** [comment]
Looked a bit more in the ontology.  Nothing jumps out.  I'd try increasing heap space.  If that doesn't fix it, we'll just have to live with it as a known bug until we switch the main server to Neo.

**Comment by Robbie1977** [comment]
On newly restarted sandbox:
```
2017-01-31 11:35:28,916 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.web.OntBeanController:53] Calling for: FBbt:00110152
2017-01-31 11:35:28,918 (vfbsandbox.inf.ed.ac.uk) DEBUG [uk.ac.ed.vfb.web.OntBeanController:59] Returned: OntBean [FBbt:00110152 octopaminergic VPM4 neuron TPB: null]
Jan 31, 2017 11:35:41 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet springmvc threw exception
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:445)
	at java.lang.StringBuffer.append(StringBuffer.java:312)
	at java.lang.StringBuffer.append(StringBuffer.java:97)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:459)
	at java.lang.StringBuffer.append(StringBuffer.java:340)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:890)
	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
	at java.lang.String.replace(String.java:2240)
	at uk.ac.ed.vfb.web.OntBeanController.resolveRefs(OntBeanController.java:183)
	at uk.ac.ed.vfb.web.OntBeanController.handleRequest(OntBeanController.java:91)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:809)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:399)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.SessionFixationProtectionFilter.doFilterHttp(SessionFixationProtectionFilter.java:67)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
```

**Comment by Robbie1977** [comment]
I'll step through the code and see what's causing it.

**Comment by Robbie1977** [comment]
Initially looks like an issue with the pub ref

**Comment by dosumis** [comment]
Refs look fine in OWL.

**Comment by Robbie1977** [comment]
think i've got it... testing

**Comment by Robbie1977** [comment]
There was an issue with the FBti link resolution causing a loop - have resolved and fix is live now.
