### ISSUE TITLE
synapsed_to null

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#373]
Found the cause of the two exceptions I spotted the other day; both FBbt_00003719 and FBbt_00003722 have relationship synapsed_to null.

I'm assuming this shouldn't be there?

**Comment by dosumis** [comment]
They both auto-synapse e.g.
lamina monopolar neuron L1 synapsed_to some lamina monopolar neuron L1

This probably looks like synapsed_to null because of hackery in the parsing.  I can fix if it is necessary  - I have Jython code that does this in a non-hacky way. What problems are caused by not fixing it?

**Comment by Robbie1977** [comment]
These are the only ones that cause the problem so seems odd. 
The relationship is not reported.

The null exception kicks up at uk.ac.ed.vfb.dao.client_server.server_includes.OwlResultParserClass.getOntBeanForClass(OwlResultParserClass.java:134)

**Comment by dosumis** [comment]
> These are the only ones that cause the problem so seems odd. 
I think they're currently the only examples of the pattern 'X R some X'.

> The null exception kicks up at uk.ac.ed.vfb.dao.client_server.server_includes.OwlResultParserClass.getOntBeanForClass(OwlResultParserClass.java:134)

OK.  I know where this is happening, but as usual, clearing through the mess will take some time and care.  Would it do any harm to leave this for a couple of weeks?

### Notes for my own reference:
2 approaches: 
* most of what is needed for a pure OWL-API approach is here:
https://github.com/VirtualFlyBrain/VFB_owl/blob/master/src/code/mod/owl2pdm_tools.py  - just need an extra check for sig array having same class twice.
* Alternatively, we can use the ogw src/code/owl_gen/migrate_exp_axioms.py

In both cases, best to run a complete local scripty test first.

**Comment by Robbie1977** [comment]
No rush as has been like this always. Just tidying.
