### ISSUE TITLE
Potential Issue with new OWL file

### ISSUE THREAD

**Issue by Robbie1977** [VirtualFlyBrain/VFB#573]
FBbt_00100247 fails to load in old format and only half loads in new layout using latest OWL files.

Works fine on live site using old OWL files.

Support info:
http://vfbsandbox.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt_00100247
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by Robbie1977** [comment]
issue appears to be with relationships:

http://vfbdev.inf.ed.ac.uk/site/tools/anatomy_finder/index.htm?id=FBbt_00100247

**Comment by Robbie1977** [comment]
2015-06-01 11:20:23,026 (vfbdev.inf.ed.ac.uk) ERROR [uk.ac.ed.vfb.dao.client_server.OWLClient:164] IOException for query: FBbt:00003345
java.net.ConnectException: Connection refused
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at java.net.Socket.connect(Socket.java:528)
at java.net.Socket.(Socket.java:425)
at java.net.Socket.(Socket.java:208)
at uk.ac.ed.vfb.dao.client_server.OWLClient$ObjectReading.run(OWLClient.java:152)

2015-06-01 11:20:23,035 (vfbdev.inf.ed.ac.uk) ERROR [uk.ac.ed.vfb.dao.client_server.OWLClient:98] null result for OWLClient.getBeanForId(FBbt:00003345)

**Comment by Robbie1977** [comment]
was caused by an Issue with the servers restart - resolved
